language: python

python:
  - "3.6"

install:
  - pip install -r docs/sphinx-requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install .

script:
  - pytest --cov=schnetpack
  
after_success:
  - coveralls
