language: python

install:
  - pip install -r docs/sphinx-requirements.txt
  - pip install coveralls
  - pip install tox

matrix:
  include:
    python: 3.6
    env: TOXENV=py36

script:
  - tox

after_success:
  - coveralls
