defaults:
  - representation: schnet

_target_: schnetpack.model.AtomisticModel

optimizer_cls: torch.optim.Adam
optimizer_args:
  lr: ${lr}

scheduler_cls: schnetpack.train.ReduceLROnPlateau
scheduler_monitor: val_loss
scheduler_args:
  mode: min
  factor: 0.5
  patience: 50
  min_lr: 1e-6
  smoothing_factor: 0.8

output_modules:
  - _target_: schnetpack.output.Atomwise
    output: energy
    n_in: ${model.representation.n_atom_basis}
    aggregation_mode: sum
  - _target_: schnetpack.output.Forces
    energy_key: energy
    force_key: forces

outputs:
  - _target_: schnetpack.model.ModelOutput
    name: energy
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: pytorch_lightning.metrics.MeanAbsoluteError
      mse:
        _target_: pytorch_lightning.metrics.MeanSquaredError
    loss_weight: 0.05
  - _target_: schnetpack.model.ModelOutput
    name: forces
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: pytorch_lightning.metrics.MeanAbsoluteError
      mse:
        _target_: pytorch_lightning.metrics.MeanSquaredError
    loss_weight: 0.95
