defaults:
  - representation: schnet
  - optimizer: null

_target_: schnetpack.model.PropertyPredictionModel
_recursive_: False

optimizer:
  _target_: torch.optim.AdamW
  lr: ${lr}
  eps: 1e-08
  weight_decay: 0.0

outputs:
  - property: ${property}
    representaton_keys: null
    requires_stats: True
    requires_atomref: True
    module:
      _target_: schnetpack.outputs.Atomwise
    loss:
      _target_: torch.nn.MSELoss
    loss_weight: 1.