defaults:
  - representation: schnet
  - optimizer: null

_target_: schnetpack.model.SinglePropertyModel
_recursive_: False

optimizer:
  _target_: torch.optim.AdamW
  lr: ${lr}
  eps: 1e-08
  weight_decay: 0.0

output:
  property: ${property}
  requires_stats: True
  requires_atomref: True

  module:
    _target_: schnetpack.outputs.Atomwise
    n_in: ${model.representation.n_atom_basis}
  loss:
    _target_: torch.nn.MSELoss