defaults:
  - representation: schnet
  - optimizer: null

_target_: schnetpack.model.PropertyPredictionModel
_recursive_: False

optimizer:
  _target_: torch.optim.AdamW
  lr: ${lr}
  eps: 1e-08
  weight_decay: 0.0

outputs:
  - property: null
    module:
      _target_: schnetpack.outputs.Atomwise
