__doc__: configuration configuration for training experiment
additional_outputs: []
dataloader:
  batch_size: 128
  mean: null
  num_train: 100
  num_val: 100
  num_workers: 4
  stddev: null
dataset:
  __doc__: configuration for the MD17 dataset
  dataset: MD17
  dbpath: ./data
  molecule: ethanol
  property_mapping:
    energy: energy
    forces: forces
device: cpu
hooks:
  __doc__: configuration for the hook ingredient
logging_hooks:
  __doc__: configuration for the logging hook ingredient
  names:
  - csv
  - tensorboard
loss_function:
  loss_tradeoff: {}
metrics:
  element_wise:
  - forces
  names: []
model:
  __doc__: configuration for the model ingredient
  coupled_interactions: false
  cutoff: 5.0
  cutoff_network: hard
  max_z: 100
  n_atom_basis: 128
  n_filters: 128
  n_gaussians: 25
  n_interactions: 6
  name: schnet
  normalize_filter: false
optimizer:
  learning_rate: 0.0001
  name: adam
overwrite: true
properties:
- energy
- forces
schedule_hooks:
  __doc__: configuration for the scheduling hook ingredient
  factor: 0.2
  min_lr: 1.0e-06
  name: reduce_on_plateau
  patience: 1
  stop_after_min: false
  window_length: 1
seed: 255801001
stopping_hooks:
  __doc__: configuration for the stopping hook ingredient
  max_epochs: null
  max_steps: null
  patience: null
  threshold_ratio: null
train_dir: training
trainer:
  __doc__: configuration for the trainer ingredient
