__doc__: configuration for the simulation experiment
calculator:
  __doc__: configuration for the calculator ingredient
  calculator: schnet_calculator
  force_conversion: 0.01944690395740863
  force_handle: forces
  position_conversion: 0.5291772105638411
  property_conversion: {}
  required_properties:
  - energy
  - forces
device: cpu
experiment_dir: ./experiments
integrator:
  __doc__: configuration for the integrator ingredient
  integrator: velocity_verlet
  time_step: 1
model_path: ./experiments/training/best_model
overwrite: true
path_to_molecules: ./data/ethanol.xyz
seed: 902643973
simulation_dir: ./experiments/simulation
simulation_steps: 1000
simulator:
  __doc__: configuration for logging hooks
  buffer_size: 1
  checkpoint_every_n_steps: 1000
  data_streams:
  - molecule_stream
  - property_stream
  log_every_n_steps: 100
  logging_hooks:
  - file_logger
  - checkpoint_logger
  restart: false
  step: 0
system:
  __doc__: configuration for the system ingredient
  n_replicas: 2
thermostat:
  __doc__: configuration for the berendsen thermostat
  bath_temperature: 50.0
  thermostat: berendsen
  transfer_time: 1.0
training_dir: ./experiments/training
