# @package _global_

defaults:
  - trainer: default_trainer
  - callbacks: default_callbacks
  - model: ???
  - data: ???
  - logger: tensorboard

work_dir: ${hydra:runtime.cwd}
data_dir: ???
name: default

print_config: True
run_dir: runs
run_id: ${uuid:1}

# hydra configuration
hydra:
    # output paths for hydra logs
    run:
        dir: ${run_dir}/${name}/${run_id}

    help:
      app_name: SchNetPack Train

      template: |-
        ${hydra.help.header}

        This is ${hydra.help.app_name}!

        == Configuration groups ==
        Compose your configuration from those groups (db=mysql)

        $APP_CONFIG_GROUPS

        == Config ==
        This is the config generated for this run.
        You can override everything, for example:
        spktrain +experiment=qm9 data_dir=/path/to/datadir
        -------
        $CONFIG
        -------

        ${hydra.help.footer}