# @package _global_

defaults:
  - mpnn_train
  - override /model: single_property
  - override /data: qm9
  - override /model/representation: painn

cutoff: 5.0
n_rbf: 20

lr: 5e-4

property: energy_U0
name: qm9_${property}


data:
  distance_unit: Ang
  property_units:
    energy_U0: eV
  transforms:
    - _target_: schnetpack.transform.SubtractCenterOfMass
    - _target_: schnetpack.transform.RemoveOffsets
      property: ${property}
      remove_atomrefs: True
      remove_mean: True
    - _target_: schnetpack.transform.TorchNeighborList
      cutoff: ${cutoff}
    - _target_: schnetpack.transform.CastTo32

