# @package _global_

defaults:
#  - trainer: default_trainer
#  - callbacks: default_callbacks
  - model: null
  - data: null
  - logger: null

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/

print_config: True


# hydra configuration
hydra:
    # output paths for hydra logs
    run:
        dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}

    searchpath:
      - file://${oc.env:PWD}